version: "3.9"

services:
  # =====================
  # PostgreSQL for Auth + Student
  # =====================
  postgres-auth:
    image: postgres:15
    container_name: postgres-auth
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: auth
    ports:
      - "5435:5432"
    volumes:
      - postgres_auth_data:/var/lib/postgresql/data

  # =====================
  # PostgreSQL for Payment
  # =====================
  postgres-student:
    image: postgres:15
    container_name: postgres-student
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: student
    ports:
      - "5434:5432"
    volumes:
      - postgres_student_data:/var/lib/postgresql/data

  # =====================
  # PostgreSQL for Notification
  # =====================
  postgres-notification:
    image: postgres:15
    container_name: postgres-notification
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: notification
    ports:
      - "5436:5432"
    volumes:
      - postgres_notification_data:/var/lib/postgresql/data

volumes:
  postgres_auth_data:
  postgres_student_data:
  postgres_notification_data:
