version: "3.9"

services:
  # =====================
  # PostgreSQL Databases
  # =====================
  postgres-user:
    image: postgres:15
    container_name: postgres-user
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: user
    ports:
      - "5435:5432"
    volumes:
      - postgres_user_data:/var/lib/postgresql/data

  postgres-student:
    image: postgres:15
    container_name: postgres-student
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: student
    ports:
      - "5434:5432"
    volumes:
      - postgres_student_data:/var/lib/postgresql/data

  postgres-notification:
    image: postgres:15
    container_name: postgres-notification
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: notification
    ports:
      - "5436:5432"
    volumes:
      - postgres_notification_data:/var/lib/postgresql/data

  postgres-transaction:
    image: postgres:15
    container_name: postgres-transaction
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: transaction
    ports:
      - "5437:5432"
    volumes:
      - postgres_transaction_data:/var/lib/postgresql/data

  # =====================
  # Redis
  # =====================
  redis:
    image: redis:7
    container_name: redis_local
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data

  # =====================
  # Backend Services
  # =====================
  user-service:
    build: ./user-service
    container_name: user-service
    command: sh -c "npx prisma generate && npx prisma migrate deploy && npm run start:dev"
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres-user:5432/user
      PORT: 4001
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - postgres-user
      - redis
    ports:
      - "4001:4001"

  student-service:
    build: ./student-service
    container_name: student-service
    command: sh -c "npx prisma generate && npx prisma migrate deploy && npm run start:dev"
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres-student:5432/student
      PORT: 4003
      USER_SERVICE: http://user-service:4001
      REDIS_HOST: redis
      REDIS_PORT: 6379
      TRANSACTION_SERVICE: http://transaction-service:4004
    depends_on:
      - postgres-student
      - user-service
      - redis
    ports:
      - "4003:4003"

  notification-service:
    build:
      context: ./notification-service

    container_name: notification-service
    command: sh -c "npx prisma generate && npx prisma migrate deploy && npm run start:dev"
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres-notification:5432/notification
      PORT: 4002
      USER_SERVICE: http://user-service:4001
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - postgres-notification
      - redis
    ports:
      - "4002:4002"

  transaction-service:
    build: ./transaction-service
    container_name: transaction-service
    command: sh -c "npx prisma generate && npx prisma migrate deploy && npm run start:dev"
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres-transaction:5432/transaction
      PORT: 4004
      USER_SERVICE: http://user-service:4001
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - postgres-transaction
      - user-service
      - redis
    ports:
      - "4004:4004"

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    command: npm run start:dev
    env_file:
      - ./api-gateway/.env.pro
    depends_on:
      - user-service
      - student-service
      - notification-service
      - transaction-service
    ports:
      - "4000:4000"


  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_URL: http://localhost:4000
    ports:
      - "3000:3000"
    depends_on:
      - api-gateway


volumes:
  postgres_user_data:
  postgres_student_data:
  postgres_notification_data:
  postgres_transaction_data:
  redis_data:
