version: "3.9"

services:
  # =====================
  # PostgreSQL for Auth + Student
  # =====================
  postgres-user:
    image: postgres:15
    container_name: postgres-user
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: user
    ports:
      - "5435:5432"
    volumes:
      - postgres_user_data:/var/lib/postgresql/data

  # =====================
  # PostgreSQL for Payment
  # =====================
  postgres-student:
    image: postgres:15
    container_name: postgres-student
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: student
    ports:
      - "5434:5432"
    volumes:
      - postgres_student_data:/var/lib/postgresql/data

  # =====================
  # PostgreSQL for Notification
  # =====================
  postgres-notification:
    image: postgres:15
    container_name: postgres-notification
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: notification
    ports:
      - "5436:5432"
    volumes:
      - postgres_notification_data:/var/lib/postgresql/data

  # =====================
  # PostgreSQL for Transaction
  # =====================
  postgres-transaction:
    image: postgres:15
    container_name: postgres-transaction
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: transaction
    ports:
      - "5437:5432"
    volumes:
      - postgres_transaction_data:/var/lib/postgresql/data

  # =====================
  # Redis for Bull Queue
  redis:
    image: redis:7
    container_name: redis_local
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data

volumes:
  postgres_user_data:
  postgres_student_data:
  postgres_notification_data:
  postgres_transaction_data:
  redis_data: